"""production hardening worker governance

Revision ID: 5bb58e96ca8a
Revises: 0e600c2583a0
Create Date: 2026-05-11 20:55:43.531734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb58e96ca8a'
down_revision = '0e600c2583a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_job_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=160), nullable=False),
    sa.Column('idempotency_key', sa.String(length=220), nullable=False),
    sa.Column('lease_name', sa.String(length=160), nullable=False),
    sa.Column('owner_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_job_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_job_run_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_job_run_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_worker_job_run_job_name'), ['job_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_job_run_lease_name'), ['lease_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_job_run_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_job_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_job_run_status'), ['status'], unique=False)

    op.create_table('worker_lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_name', sa.String(length=160), nullable=False),
    sa.Column('owner_id', sa.String(length=160), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_lease_acquired_at'), ['acquired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_lease_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_lease_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_lease_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_lease_lease_name'), ['lease_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_worker_lease_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_lease_status'), ['status'], unique=False)

    op.create_table('ml_model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=180), nullable=False),
    sa.Column('offline_model_id', sa.Integer(), nullable=True),
    sa.Column('model_family', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('feature_schema_hash', sa.String(length=128), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=False),
    sa.Column('dataset_hash', sa.String(length=128), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_by', sa.String(length=120), nullable=False),
    sa.Column('promotion_source', sa.String(length=120), nullable=False),
    sa.Column('rollback_target_model_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('drift_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offline_model_id'], ['ml_offline_model.id'], ),
    sa.ForeignKeyConstraint(['rollback_target_model_id'], ['ml_offline_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_model_registry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_drift_status'), ['drift_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_horizon'), ['horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_model_family'), ['model_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_model_key'), ['model_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_offline_model_id'), ['offline_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_promoted_at'), ['promoted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_rollback_target_model_id'), ['rollback_target_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_model_registry_trained_at'), ['trained_at'], unique=False)

    with op.batch_alter_table('ml_offline_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_schema_hash', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('dataset_version', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('dataset_hash', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('training_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('training_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('promoted_by', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('promotion_source', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('rollback_target_model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('live_mode', sa.String(length=32), nullable=False, server_default='shadow'))
        batch_op.add_column(sa.Column('drift_status', sa.String(length=32), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('governance_metadata_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_ml_offline_model_drift_status'), ['drift_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_offline_model_live_mode'), ['live_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_offline_model_rollback_target_model_id'), ['rollback_target_model_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_ml_offline_model_rollback_target_model_id',
            'ml_offline_model',
            ['rollback_target_model_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_offline_model', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ml_offline_model_rollback_target_model_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ml_offline_model_rollback_target_model_id'))
        batch_op.drop_index(batch_op.f('ix_ml_offline_model_live_mode'))
        batch_op.drop_index(batch_op.f('ix_ml_offline_model_drift_status'))
        batch_op.drop_column('governance_metadata_json')
        batch_op.drop_column('drift_status')
        batch_op.drop_column('live_mode')
        batch_op.drop_column('rollback_target_model_id')
        batch_op.drop_column('promotion_source')
        batch_op.drop_column('promoted_by')
        batch_op.drop_column('training_completed_at')
        batch_op.drop_column('training_started_at')
        batch_op.drop_column('dataset_hash')
        batch_op.drop_column('dataset_version')
        batch_op.drop_column('feature_schema_hash')

    with op.batch_alter_table('ml_model_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_trained_at'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_status'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_rollback_target_model_id'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_provider'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_promoted_at'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_offline_model_id'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_model_version'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_model_key'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_model_family'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_mode'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_horizon'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_drift_status'))
        batch_op.drop_index(batch_op.f('ix_ml_model_registry_created_at'))

    op.drop_table('ml_model_registry')
    with op.batch_alter_table('worker_lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_lease_status'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_owner_id'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_lease_name'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_heartbeat_at'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_created_at'))
        batch_op.drop_index(batch_op.f('ix_worker_lease_acquired_at'))

    op.drop_table('worker_lease')
    with op.batch_alter_table('worker_job_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_job_run_status'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_owner_id'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_lease_name'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_job_name'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_worker_job_run_completed_at'))

    op.drop_table('worker_job_run')
    # ### end Alembic commands ###
